AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Rails:
  Enabled: true
